-- --------------------------------------------------------
-- Διακομιστής:                  127.0.0.1
-- Έκδοση διακομιστή:            10.4.28-MariaDB - mariadb.org binary distribution
-- Λειτ. σύστημα διακομιστή:     Win64
-- HeidiSQL Έκδοση:              12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for πίνακας battleshipgamedb.board
CREATE TABLE IF NOT EXISTS `board` (
  `player` enum('p1','p2') NOT NULL,
  `coordinate` varchar(3) NOT NULL,
  `ship` enum('Destroyer','Submarine','Cruiser','Battleship','Carrier') DEFAULT NULL,
  `state` enum('empty','ship','hit','miss') NOT NULL DEFAULT 'empty'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table battleshipgamedb.board: ~200 rows (approximately)
INSERT INTO `board` (`player`, `coordinate`, `ship`, `state`) VALUES
	('p1', 'A1', NULL, 'empty'),
	('p1', 'A2', NULL, 'empty'),
	('p1', 'A3', NULL, 'empty'),
	('p1', 'A4', NULL, 'empty'),
	('p1', 'A5', NULL, 'empty'),
	('p1', 'A6', NULL, 'empty'),
	('p1', 'A7', NULL, 'empty'),
	('p1', 'A8', NULL, 'empty'),
	('p1', 'A9', NULL, 'empty'),
	('p1', 'A10', NULL, 'empty'),
	('p1', 'B1', NULL, 'empty'),
	('p1', 'B2', NULL, 'empty'),
	('p1', 'B3', NULL, 'empty'),
	('p1', 'B4', NULL, 'empty'),
	('p1', 'B5', NULL, 'empty'),
	('p1', 'B6', NULL, 'empty'),
	('p1', 'B7', NULL, 'empty'),
	('p1', 'B8', NULL, 'empty'),
	('p1', 'B9', NULL, 'empty'),
	('p1', 'B10', NULL, 'empty'),
	('p1', 'C1', NULL, 'empty'),
	('p1', 'C2', NULL, 'empty'),
	('p1', 'C3', NULL, 'empty'),
	('p1', 'C4', NULL, 'empty'),
	('p1', 'C5', NULL, 'empty'),
	('p1', 'C6', NULL, 'empty'),
	('p1', 'C7', NULL, 'empty'),
	('p1', 'C8', NULL, 'empty'),
	('p1', 'C9', NULL, 'empty'),
	('p1', 'C10', NULL, 'empty'),
	('p1', 'D1', NULL, 'empty'),
	('p1', 'D2', NULL, 'empty'),
	('p1', 'D3', NULL, 'empty'),
	('p1', 'D4', NULL, 'empty'),
	('p1', 'D5', NULL, 'empty'),
	('p1', 'D6', NULL, 'empty'),
	('p1', 'D7', NULL, 'empty'),
	('p1', 'D8', NULL, 'empty'),
	('p1', 'D9', NULL, 'empty'),
	('p1', 'D10', NULL, 'empty'),
	('p1', 'E1', NULL, 'empty'),
	('p1', 'E2', NULL, 'empty'),
	('p1', 'E3', NULL, 'empty'),
	('p1', 'E4', NULL, 'empty'),
	('p1', 'E5', NULL, 'empty'),
	('p1', 'E6', NULL, 'empty'),
	('p1', 'E7', NULL, 'empty'),
	('p1', 'E8', NULL, 'empty'),
	('p1', 'E9', NULL, 'empty'),
	('p1', 'E10', NULL, 'empty'),
	('p1', 'F1', NULL, 'empty'),
	('p1', 'F2', NULL, 'empty'),
	('p1', 'F3', NULL, 'empty'),
	('p1', 'F4', NULL, 'empty'),
	('p1', 'F5', NULL, 'empty'),
	('p1', 'F6', NULL, 'empty'),
	('p1', 'F7', NULL, 'empty'),
	('p1', 'F8', NULL, 'empty'),
	('p1', 'F9', NULL, 'empty'),
	('p1', 'F10', NULL, 'empty'),
	('p1', 'G1', NULL, 'empty'),
	('p1', 'G2', NULL, 'empty'),
	('p1', 'G3', NULL, 'empty'),
	('p1', 'G4', NULL, 'empty'),
	('p1', 'G5', NULL, 'empty'),
	('p1', 'G6', NULL, 'empty'),
	('p1', 'G7', NULL, 'empty'),
	('p1', 'G8', NULL, 'empty'),
	('p1', 'G9', NULL, 'empty'),
	('p1', 'G10', NULL, 'empty'),
	('p1', 'H1', NULL, 'empty'),
	('p1', 'H2', NULL, 'empty'),
	('p1', 'H3', NULL, 'empty'),
	('p1', 'H4', NULL, 'empty'),
	('p1', 'H5', NULL, 'empty'),
	('p1', 'H6', NULL, 'empty'),
	('p1', 'H7', NULL, 'empty'),
	('p1', 'H8', NULL, 'empty'),
	('p1', 'H9', NULL, 'empty'),
	('p1', 'H10', NULL, 'empty'),
	('p1', 'I1', NULL, 'empty'),
	('p1', 'I2', NULL, 'empty'),
	('p1', 'I3', NULL, 'empty'),
	('p1', 'I4', NULL, 'empty'),
	('p1', 'I5', NULL, 'empty'),
	('p1', 'I6', NULL, 'empty'),
	('p1', 'I7', NULL, 'empty'),
	('p1', 'I8', NULL, 'empty'),
	('p1', 'I9', NULL, 'empty'),
	('p1', 'I10', NULL, 'empty'),
	('p1', 'J1', NULL, 'empty'),
	('p1', 'J2', NULL, 'empty'),
	('p1', 'J3', NULL, 'empty'),
	('p1', 'J4', NULL, 'empty'),
	('p1', 'J5', NULL, 'empty'),
	('p1', 'J6', NULL, 'empty'),
	('p1', 'J7', NULL, 'empty'),
	('p1', 'J8', NULL, 'empty'),
	('p1', 'J9', NULL, 'empty'),
	('p1', 'J10', NULL, 'empty'),
	('p2', 'A1', NULL, 'empty'),
	('p2', 'A2', NULL, 'empty'),
	('p2', 'A3', NULL, 'empty'),
	('p2', 'A4', NULL, 'empty'),
	('p2', 'A5', NULL, 'empty'),
	('p2', 'A6', NULL, 'empty'),
	('p2', 'A7', NULL, 'empty'),
	('p2', 'A8', NULL, 'empty'),
	('p2', 'A9', NULL, 'empty'),
	('p2', 'A10', NULL, 'empty'),
	('p2', 'B1', NULL, 'empty'),
	('p2', 'B2', NULL, 'empty'),
	('p2', 'B3', NULL, 'empty'),
	('p2', 'B4', NULL, 'empty'),
	('p2', 'B5', NULL, 'empty'),
	('p2', 'B6', NULL, 'empty'),
	('p2', 'B7', NULL, 'empty'),
	('p2', 'B8', NULL, 'empty'),
	('p2', 'B9', NULL, 'empty'),
	('p2', 'B10', NULL, 'empty'),
	('p2', 'C1', NULL, 'empty'),
	('p2', 'C2', NULL, 'empty'),
	('p2', 'C3', NULL, 'empty'),
	('p2', 'C4', NULL, 'empty'),
	('p2', 'C5', NULL, 'empty'),
	('p2', 'C6', NULL, 'empty'),
	('p2', 'C7', NULL, 'empty'),
	('p2', 'C8', NULL, 'empty'),
	('p2', 'C9', NULL, 'empty'),
	('p2', 'C10', NULL, 'empty'),
	('p2', 'D1', NULL, 'empty'),
	('p2', 'D2', NULL, 'empty'),
	('p2', 'D3', NULL, 'empty'),
	('p2', 'D4', NULL, 'empty'),
	('p2', 'D5', NULL, 'empty'),
	('p2', 'D6', NULL, 'empty'),
	('p2', 'D7', NULL, 'empty'),
	('p2', 'D8', NULL, 'empty'),
	('p2', 'D9', NULL, 'empty'),
	('p2', 'D10', NULL, 'empty'),
	('p2', 'E1', NULL, 'empty'),
	('p2', 'E2', NULL, 'empty'),
	('p2', 'E3', NULL, 'empty'),
	('p2', 'E4', NULL, 'empty'),
	('p2', 'E5', NULL, 'empty'),
	('p2', 'E6', NULL, 'empty'),
	('p2', 'E7', NULL, 'empty'),
	('p2', 'E8', NULL, 'empty'),
	('p2', 'E9', NULL, 'empty'),
	('p2', 'E10', NULL, 'empty'),
	('p2', 'F1', NULL, 'empty'),
	('p2', 'F2', NULL, 'empty'),
	('p2', 'F3', NULL, 'empty'),
	('p2', 'F4', NULL, 'empty'),
	('p2', 'F5', NULL, 'empty'),
	('p2', 'F6', NULL, 'empty'),
	('p2', 'F7', NULL, 'empty'),
	('p2', 'F8', NULL, 'empty'),
	('p2', 'F9', NULL, 'empty'),
	('p2', 'F10', NULL, 'empty'),
	('p2', 'G1', NULL, 'empty'),
	('p2', 'G2', NULL, 'empty'),
	('p2', 'G3', NULL, 'empty'),
	('p2', 'G4', NULL, 'empty'),
	('p2', 'G5', NULL, 'empty'),
	('p2', 'G6', NULL, 'empty'),
	('p2', 'G7', NULL, 'empty'),
	('p2', 'G8', NULL, 'empty'),
	('p2', 'G9', NULL, 'empty'),
	('p2', 'G10', NULL, 'empty'),
	('p2', 'H1', NULL, 'empty'),
	('p2', 'H2', NULL, 'empty'),
	('p2', 'H3', NULL, 'empty'),
	('p2', 'H4', NULL, 'empty'),
	('p2', 'H5', NULL, 'empty'),
	('p2', 'H6', NULL, 'empty'),
	('p2', 'H7', NULL, 'empty'),
	('p2', 'H8', NULL, 'empty'),
	('p2', 'H9', NULL, 'empty'),
	('p2', 'H10', NULL, 'empty'),
	('p2', 'I1', NULL, 'empty'),
	('p2', 'I2', NULL, 'empty'),
	('p2', 'I3', NULL, 'empty'),
	('p2', 'I4', NULL, 'empty'),
	('p2', 'I5', NULL, 'empty'),
	('p2', 'I6', NULL, 'empty'),
	('p2', 'I7', NULL, 'empty'),
	('p2', 'I8', NULL, 'empty'),
	('p2', 'I9', NULL, 'empty'),
	('p2', 'I10', NULL, 'empty'),
	('p2', 'J1', NULL, 'empty'),
	('p2', 'J2', NULL, 'empty'),
	('p2', 'J3', NULL, 'empty'),
	('p2', 'J4', NULL, 'empty'),
	('p2', 'J5', NULL, 'empty'),
	('p2', 'J6', NULL, 'empty'),
	('p2', 'J7', NULL, 'empty'),
	('p2', 'J8', NULL, 'empty'),
	('p2', 'J9', NULL, 'empty'),
	('p2', 'J10', NULL, 'empty');

-- Dumping structure for πίνακας battleshipgamedb.board_empty
CREATE TABLE IF NOT EXISTS `board_empty` (
  `player` enum('p1','p2') NOT NULL,
  `coordinate` varchar(3) NOT NULL,
  `ship` enum('Destroyer','Submarine','Cruiser','Battleship','Carrier') DEFAULT NULL,
  `state` enum('empty','ship','hit','miss') NOT NULL DEFAULT 'empty'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table battleshipgamedb.board_empty: ~200 rows (approximately)
INSERT INTO `board_empty` (`player`, `coordinate`, `ship`, `state`) VALUES
	('p1', 'A1', NULL, 'empty'),
	('p1', 'A2', NULL, 'empty'),
	('p1', 'A3', NULL, 'empty'),
	('p1', 'A4', NULL, 'empty'),
	('p1', 'A5', NULL, 'empty'),
	('p1', 'A6', NULL, 'empty'),
	('p1', 'A7', NULL, 'empty'),
	('p1', 'A8', NULL, 'empty'),
	('p1', 'A9', NULL, 'empty'),
	('p1', 'A10', NULL, 'empty'),
	('p1', 'B1', NULL, 'empty'),
	('p1', 'B2', NULL, 'empty'),
	('p1', 'B3', NULL, 'empty'),
	('p1', 'B4', NULL, 'empty'),
	('p1', 'B5', NULL, 'empty'),
	('p1', 'B6', NULL, 'empty'),
	('p1', 'B7', NULL, 'empty'),
	('p1', 'B8', NULL, 'empty'),
	('p1', 'B9', NULL, 'empty'),
	('p1', 'B10', NULL, 'empty'),
	('p1', 'C1', NULL, 'empty'),
	('p1', 'C2', NULL, 'empty'),
	('p1', 'C3', NULL, 'empty'),
	('p1', 'C4', NULL, 'empty'),
	('p1', 'C5', NULL, 'empty'),
	('p1', 'C6', NULL, 'empty'),
	('p1', 'C7', NULL, 'empty'),
	('p1', 'C8', NULL, 'empty'),
	('p1', 'C9', NULL, 'empty'),
	('p1', 'C10', NULL, 'empty'),
	('p1', 'D1', NULL, 'empty'),
	('p1', 'D2', NULL, 'empty'),
	('p1', 'D3', NULL, 'empty'),
	('p1', 'D4', NULL, 'empty'),
	('p1', 'D5', NULL, 'empty'),
	('p1', 'D6', NULL, 'empty'),
	('p1', 'D7', NULL, 'empty'),
	('p1', 'D8', NULL, 'empty'),
	('p1', 'D9', NULL, 'empty'),
	('p1', 'D10', NULL, 'empty'),
	('p1', 'E1', NULL, 'empty'),
	('p1', 'E2', NULL, 'empty'),
	('p1', 'E3', NULL, 'empty'),
	('p1', 'E4', NULL, 'empty'),
	('p1', 'E5', NULL, 'empty'),
	('p1', 'E6', NULL, 'empty'),
	('p1', 'E7', NULL, 'empty'),
	('p1', 'E8', NULL, 'empty'),
	('p1', 'E9', NULL, 'empty'),
	('p1', 'E10', NULL, 'empty'),
	('p1', 'F1', NULL, 'empty'),
	('p1', 'F2', NULL, 'empty'),
	('p1', 'F3', NULL, 'empty'),
	('p1', 'F4', NULL, 'empty'),
	('p1', 'F5', NULL, 'empty'),
	('p1', 'F6', NULL, 'empty'),
	('p1', 'F7', NULL, 'empty'),
	('p1', 'F8', NULL, 'empty'),
	('p1', 'F9', NULL, 'empty'),
	('p1', 'F10', NULL, 'empty'),
	('p1', 'G1', NULL, 'empty'),
	('p1', 'G2', NULL, 'empty'),
	('p1', 'G3', NULL, 'empty'),
	('p1', 'G4', NULL, 'empty'),
	('p1', 'G5', NULL, 'empty'),
	('p1', 'G6', NULL, 'empty'),
	('p1', 'G7', NULL, 'empty'),
	('p1', 'G8', NULL, 'empty'),
	('p1', 'G9', NULL, 'empty'),
	('p1', 'G10', NULL, 'empty'),
	('p1', 'H1', NULL, 'empty'),
	('p1', 'H2', NULL, 'empty'),
	('p1', 'H3', NULL, 'empty'),
	('p1', 'H4', NULL, 'empty'),
	('p1', 'H5', NULL, 'empty'),
	('p1', 'H6', NULL, 'empty'),
	('p1', 'H7', NULL, 'empty'),
	('p1', 'H8', NULL, 'empty'),
	('p1', 'H9', NULL, 'empty'),
	('p1', 'H10', NULL, 'empty'),
	('p1', 'I1', NULL, 'empty'),
	('p1', 'I2', NULL, 'empty'),
	('p1', 'I3', NULL, 'empty'),
	('p1', 'I4', NULL, 'empty'),
	('p1', 'I5', NULL, 'empty'),
	('p1', 'I6', NULL, 'empty'),
	('p1', 'I7', NULL, 'empty'),
	('p1', 'I8', NULL, 'empty'),
	('p1', 'I9', NULL, 'empty'),
	('p1', 'I10', NULL, 'empty'),
	('p1', 'J1', NULL, 'empty'),
	('p1', 'J2', NULL, 'empty'),
	('p1', 'J3', NULL, 'empty'),
	('p1', 'J4', NULL, 'empty'),
	('p1', 'J5', NULL, 'empty'),
	('p1', 'J6', NULL, 'empty'),
	('p1', 'J7', NULL, 'empty'),
	('p1', 'J8', NULL, 'empty'),
	('p1', 'J9', NULL, 'empty'),
	('p1', 'J10', NULL, 'empty'),
	('p2', 'A1', NULL, 'empty'),
	('p2', 'A2', NULL, 'empty'),
	('p2', 'A3', NULL, 'empty'),
	('p2', 'A4', NULL, 'empty'),
	('p2', 'A5', NULL, 'empty'),
	('p2', 'A6', NULL, 'empty'),
	('p2', 'A7', NULL, 'empty'),
	('p2', 'A8', NULL, 'empty'),
	('p2', 'A9', NULL, 'empty'),
	('p2', 'A10', NULL, 'empty'),
	('p2', 'B1', NULL, 'empty'),
	('p2', 'B2', NULL, 'empty'),
	('p2', 'B3', NULL, 'empty'),
	('p2', 'B4', NULL, 'empty'),
	('p2', 'B5', NULL, 'empty'),
	('p2', 'B6', NULL, 'empty'),
	('p2', 'B7', NULL, 'empty'),
	('p2', 'B8', NULL, 'empty'),
	('p2', 'B9', NULL, 'empty'),
	('p2', 'B10', NULL, 'empty'),
	('p2', 'C1', NULL, 'empty'),
	('p2', 'C2', NULL, 'empty'),
	('p2', 'C3', NULL, 'empty'),
	('p2', 'C4', NULL, 'empty'),
	('p2', 'C5', NULL, 'empty'),
	('p2', 'C6', NULL, 'empty'),
	('p2', 'C7', NULL, 'empty'),
	('p2', 'C8', NULL, 'empty'),
	('p2', 'C9', NULL, 'empty'),
	('p2', 'C10', NULL, 'empty'),
	('p2', 'D1', NULL, 'empty'),
	('p2', 'D2', NULL, 'empty'),
	('p2', 'D3', NULL, 'empty'),
	('p2', 'D4', NULL, 'empty'),
	('p2', 'D5', NULL, 'empty'),
	('p2', 'D6', NULL, 'empty'),
	('p2', 'D7', NULL, 'empty'),
	('p2', 'D8', NULL, 'empty'),
	('p2', 'D9', NULL, 'empty'),
	('p2', 'D10', NULL, 'empty'),
	('p2', 'E1', NULL, 'empty'),
	('p2', 'E2', NULL, 'empty'),
	('p2', 'E3', NULL, 'empty'),
	('p2', 'E4', NULL, 'empty'),
	('p2', 'E5', NULL, 'empty'),
	('p2', 'E6', NULL, 'empty'),
	('p2', 'E7', NULL, 'empty'),
	('p2', 'E8', NULL, 'empty'),
	('p2', 'E9', NULL, 'empty'),
	('p2', 'E10', NULL, 'empty'),
	('p2', 'F1', NULL, 'empty'),
	('p2', 'F2', NULL, 'empty'),
	('p2', 'F3', NULL, 'empty'),
	('p2', 'F4', NULL, 'empty'),
	('p2', 'F5', NULL, 'empty'),
	('p2', 'F6', NULL, 'empty'),
	('p2', 'F7', NULL, 'empty'),
	('p2', 'F8', NULL, 'empty'),
	('p2', 'F9', NULL, 'empty'),
	('p2', 'F10', NULL, 'empty'),
	('p2', 'G1', NULL, 'empty'),
	('p2', 'G2', NULL, 'empty'),
	('p2', 'G3', NULL, 'empty'),
	('p2', 'G4', NULL, 'empty'),
	('p2', 'G5', NULL, 'empty'),
	('p2', 'G6', NULL, 'empty'),
	('p2', 'G7', NULL, 'empty'),
	('p2', 'G8', NULL, 'empty'),
	('p2', 'G9', NULL, 'empty'),
	('p2', 'G10', NULL, 'empty'),
	('p2', 'H1', NULL, 'empty'),
	('p2', 'H2', NULL, 'empty'),
	('p2', 'H3', NULL, 'empty'),
	('p2', 'H4', NULL, 'empty'),
	('p2', 'H5', NULL, 'empty'),
	('p2', 'H6', NULL, 'empty'),
	('p2', 'H7', NULL, 'empty'),
	('p2', 'H8', NULL, 'empty'),
	('p2', 'H9', NULL, 'empty'),
	('p2', 'H10', NULL, 'empty'),
	('p2', 'I1', NULL, 'empty'),
	('p2', 'I2', NULL, 'empty'),
	('p2', 'I3', NULL, 'empty'),
	('p2', 'I4', NULL, 'empty'),
	('p2', 'I5', NULL, 'empty'),
	('p2', 'I6', NULL, 'empty'),
	('p2', 'I7', NULL, 'empty'),
	('p2', 'I8', NULL, 'empty'),
	('p2', 'I9', NULL, 'empty'),
	('p2', 'I10', NULL, 'empty'),
	('p2', 'J1', NULL, 'empty'),
	('p2', 'J2', NULL, 'empty'),
	('p2', 'J3', NULL, 'empty'),
	('p2', 'J4', NULL, 'empty'),
	('p2', 'J5', NULL, 'empty'),
	('p2', 'J6', NULL, 'empty'),
	('p2', 'J7', NULL, 'empty'),
	('p2', 'J8', NULL, 'empty'),
	('p2', 'J9', NULL, 'empty'),
	('p2', 'J10', NULL, 'empty');

-- Dumping structure for procedure battleshipgamedb.clean_board
DELIMITER //
CREATE PROCEDURE `clean_board`()
BEGIN
      TRUNCATE TABLE board;
      REPLACE INTO board SELECT * FROM board_empty;
      
      UPDATE players SET username=NULL, token=NULL, last_action=NULL;
      UPDATE game_status SET status='not active', player_turn=NULL, result=NULL;
END//
DELIMITER ;

-- Dumping structure for πίνακας battleshipgamedb.game_status
CREATE TABLE IF NOT EXISTS `game_status` (
  `status` enum('not active','initialized','started','ended','aborded') NOT NULL DEFAULT 'not active',
  `player_turn` enum('p1','p2') DEFAULT NULL,
  `result` enum('p1','p2') DEFAULT NULL,
  `last_change` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table battleshipgamedb.game_status: ~1 rows (approximately)
INSERT INTO `game_status` (`status`, `player_turn`, `result`, `last_change`) VALUES
	('not active', NULL, NULL, '2023-11-30 10:00:00');

-- Dumping structure for πίνακας battleshipgamedb.players
CREATE TABLE IF NOT EXISTS `players` (
  `username` varchar(10) DEFAULT NULL,
  `player_number` enum('p1','p2') NOT NULL,
  `token` varchar(100) DEFAULT NULL,
  `last_action` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`player_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table battleshipgamedb.players: ~2 rows (approximately)
INSERT INTO `players` (`username`, `player_number`, `token`, `last_action`) VALUES
	(NULL, 'p1', NULL, '2023-11-30 10:00:00'),
	(NULL, 'p2', NULL, '2023-11-30 10:00:00');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
